### ISSUE TITLE
Remove empty app module, leaving only the library

### ISSUE THREAD

**Issue by cdflynn** [zetaapps/either#1]
I notice the main activity is still empty, I removed it on the other libraries (utils, etc).  We could do the same here, unless you prefer to show sample usage there.  It keeps the footprint as small as possible.

If so, we can also trash everything in `res`

**Comment by manjunathc23** [comment]
👍  I will do that, Good idea.

**Comment by manjunathc23** [comment]
Done : @cdflynn  Thanks for the feedback.
